#/*****************************************************************************************
#  *
#  * Pipeline for Ovarian cancer analysis - Copyright (C) <2017-2023> <Université catholique de Louvain (UCLouvain)>
#  * 	
#  * List of the contributors to the development of Excalibur simulation: see LICENSE file.
#* Description and complete License: see LICENSE file.
#* 	
#  * This program (Excalibur simulation) is free software: 
#  * you can redistribute it and/or modify it under the terms of the 
#* GNU General Public License as published by the Free Software Foundation, 
#* either version 3 of the License, or (at your option) any later version.
#* 
#  * This program is distributed in the hope that it will be useful,
#* but WITHOUT ANY WARRANTY; without even the implied warranty of
#* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#* GNU General Public License for more details.
#* 
#  * You should have received a copy of the GNU General Public License
#* along with this program (see COPYING file).  If not, 
#* see <http://www.gnu.org/licenses/>.
#* 
#  *****************************************************************************************/
#  
#  /**
#  *
#  * @author Simon Boutry
#*
#  */

#' combined_analysis_mutation_and_facets
#'
#' MAKE DESCRIPTION
#' 
#' @param path_clean_mutation path to mutation file as outputed by Mutation_analysis() function
#' @param path_indi_gene path to patient_indiv genes file as outputed by Facets_analysis() function
#' @param clinical_data_path path to clinical data 
#' @param path_cancer_gene path to file with cancer gene list with mandatory columns Hugo_Symbol and for analysis "oncoGene_and_tumorSupr" also Is_Oncogene Is_Tumor_Suppressor_Gene
#' @param analysis_to_do name of analysis to perform, or Default, or oncoGene_and_tumorSupr or both
#' @param group_to_plot which group of should be analyzed (ASC, TuPo, TuPr) 
#' @param min_occurence_gene minimum number of time a gene is present in combined data (mutation + Facets) to be taken into account in the analysis
#' @param path_output where to store results
#'
#'
combined_analysis_mutation_and_facets <- function(path_clean_mutation = "",
                                                  path_sig_mutation = "",
                                                  path_indi_gene = "",
                                                  clinical_data_path = "",
                                                  path_cancer_gene = "",
                                                  analysis_to_do = c("Default", "oncoGene_and_tumorSupr"),
                                                  group_to_plot = c("ASC", "TuPr", "TuPo"),
                                                  min_occurence_gene = 2,
                                                  path_output = getwd()){
  #libraries
  library(readxl)
  library(tidyverse)
  library(RColorBrewer)
  library(ComplexHeatmap)
  library(UpSetR)
  library(survival)
  library(ggrepel)
  library(writexl)
  library(cowplot)
  
  
  dir.create(path_output)
  #import the clinical data of your samples
  clinical_data <- read_xlsx(clinical_data_path)
  #TODO as argument of the function : patient_to_rm, for the moment only remove the patient from the clinical data (carefull with facets/mutation)
  #patient_to_rm <- c("KDAU")
  
  clinical_data <- clinical_data[which(!is.na(clinical_data$Anapath_response)),]
  #clinical_data <- clinical_data[-which(clinical_data$Patient == patient_to_rm),]
  clinical_data$Anapath_response <- factor(clinical_data$Anapath_response,
                                           levels = c("Good", "Intermediate", "Bad"))
  #Reorder for plot
  clinical_data <- clinical_data %>%
    arrange(Anapath_response, desc(DFS))
  
  #import the mutations calls directly exported from highlander
  mutation_data <- read_tsv(path_clean_mutation)
  mutation_data$sample <- gsub("VDB-", "", mutation_data$sample)
  mutation_data$Patient_name <- substr(mutation_data$sample, 1, 4)
  
  #import mutation significantly depleted/enriched
  enrich_mutation_data <- read_tsv(path_sig_mutation)
  enrich_mutation_data$sample <- gsub("VDB-", "", enrich_mutation_data$sample)
  enrich_mutation_data$Patient_name <- substr(enrich_mutation_data$sample, 1, 4)
  
  #check if patient in mutation data are not present in clinical data
  missing_clinical_info <- which(!unique(mutation_data$Patient_name) %in% unique(clinical_data$Patient))
  if(length(missing_clinical_info) > 0){
    stop(paste("Mutation data but not present in clinical data for patient", unique(mutation_data$Patient_name)[missing_clinical_info]))
  }
  
  #import cancer gene list
  cancer_gene_list <- read_tsv(path_cancer_gene)
  
  #import the CNV calls that was generated by the CNV calling script, from the Facets data exported from Highlander
  facets_individual_gene <- read_tsv(path_indi_gene)
  facets_individual_gene$Patient <- gsub("VDB-", "", facets_individual_gene$Patient)
  facets_individual_gene$Patient_name <- substr(facets_individual_gene$Patient, 1, 4)
  #filter cnv based on cancer gene list
  facets_individual_gene <- facets_individual_gene[which(facets_individual_gene$genes_of_interest %in% cancer_gene_list$Hugo_Symbol),]
  to_rm <- c()
  for (i in 1:dim(facets_individual_gene)[1]) {
    tmp <- facets_individual_gene[i,]
    #remove all AMP in Not oncogene and isTumor
    if(tmp$CN_interpretation =="gain"){
      tmp_isOnco <- cancer_gene_list$Is_Oncogene[which(cancer_gene_list$Hugo_Symbol == tmp$genes_of_interest)]
      tmp_isTumorSUp <- cancer_gene_list$Is_Tumor_Suppressor_Gene[which(cancer_gene_list$Hugo_Symbol == tmp$genes_of_interest)]
      if(tmp_isOnco == "No" && tmp_isTumorSUp == "Yes"){
        to_rm <- c(to_rm, i)
      }
    }
    #remove all AMP in Not oncogene and isTumor
    if(tmp$CN_interpretation =="del"){
      tmp_isOnco <- cancer_gene_list$Is_Oncogene[which(cancer_gene_list$Hugo_Symbol == tmp$genes_of_interest)]
      tmp_isTumorSUp <- cancer_gene_list$Is_Tumor_Suppressor_Gene[which(cancer_gene_list$Hugo_Symbol == tmp$genes_of_interest)]
      if(tmp_isOnco == "Yes" && tmp_isTumorSUp == "No"){
        to_rm <- c(to_rm, i)
      }
    }
  }
  
  facets_individual_gene <- facets_individual_gene[-to_rm,]
  
  ###TODO add facets info for the mail of cedric
  
  #check if patient in mutation data are not present in clinical data
  missing_clinical_info <- which(!unique(facets_individual_gene$Patient_name) %in% unique(clinical_data$Patient))
  if(length(missing_clinical_info) > 0){
    stop(paste("Facets individual_gene data but not present in clinical data for patient", unique(facets_individual_gene$Patient_name)[missing_clinical_info]))
  }
  
  #remove all mutation in oncogene with snep effect START_LOST", "STOP_GAINED", "STOP_LOST", "FRAME_SHIFT
  tmp_id <- which(mutation_data$gene_symbol %in% cancer_gene_list$Hugo_Symbol[which(cancer_gene_list$Is_Oncogene == "Yes")])
  tmp_to_rm <- which(mutation_data$snpeff_effect[tmp_id] %in% c("START_LOST", "STOP_GAINED", "STOP_LOST", "FRAME_SHIFT"))
  if(length(tmp_to_rm) > 0){
    mutation_data <- mutation_data[-tmp_id[tmp_to_rm],]
  }
  
  #same but for significantly depleted/enrich mutation
  tmp_id <- which(enrich_mutation_data$gene_symbol %in% cancer_gene_list$Hugo_Symbol[which(cancer_gene_list$Is_Oncogene == "Yes")])
  tmp_to_rm <- which(enrich_mutation_data$snpeff_effect[tmp_id] %in% c("START_LOST", "STOP_GAINED", "STOP_LOST", "FRAME_SHIFT"))
  if(length(tmp_to_rm) > 0){
    enrich_mutation_data <- enrich_mutation_data[-tmp_id[tmp_to_rm],]
  }
  
  list_data <- vector(mode = "list", length = length(group_to_plot))
  list_combined_gene <- vector(mode = "list", length = length(group_to_plot))
  count <- 1
  #Create matrices 
  for (group in group_to_plot) {
    #TODO what list of patient to use
    patient_list <- unique(clinical_data$Patient)
    nbr_patient <- length(patient_list)
    
    #keep data for group of interest
    mutation_group <- mutation_data[grep(mutation_data$sample, pattern = group),]
    
    cnv_group <- facets_individual_gene[grep(facets_individual_gene$Patient, pattern = group),]
    
    #Filter on different type of cnv (cedric get rid of LOH, keep and separate gain and del)
    amp_cnv_group <- cnv_group[which(cnv_group$CN_interpretation == "gain"),]
    del_cnv_group <- cnv_group[which(cnv_group$CN_interpretation == "del"),]
    
    #combined gene list of mutation, amplification_cnv and deletion_cnv AND remove NA, count a gene only once per patient
    combined_gene_list <- c()
    for (i in 1:nbr_patient) {
      tmp <- unique(c(mutation_group$gene_symbol[which(mutation_group$sample == paste(patient_list[i], group, sep = "-"))],
                      amp_cnv_group$genes_of_interest[which(amp_cnv_group$Patient == paste(patient_list[i], group, sep = "-"))],
                      del_cnv_group$genes_of_interest[which(del_cnv_group$Patient == paste(patient_list[i], group, sep = "-"))]))
      combined_gene_list <- c(combined_gene_list, tmp)
    }
    combined_gene_list <- combined_gene_list[which(!is.na(combined_gene_list))]
    combined_gene_list <- data.frame(table(combined_gene_list))
    list_combined_gene[[count]] <- combined_gene_list
    names(list_combined_gene)[[count]] <- group
    
    #TODO change 2 ? 
    to_plot_gene_nbr <- combined_gene_list[which(combined_gene_list$Freq >=2),]
    min_x <- min(unique(to_plot_gene_nbr$Freq))
    max_x <- max(unique(to_plot_gene_nbr$Freq))
    g <- ggplot(to_plot_gene_nbr, aes(Freq)) +
      geom_histogram() +
      scale_x_continuous(breaks = min_x:max_x) +
      xlab(paste("How many time a gene is present in data for", group)) +
      ylab("Number of gene") +
      theme_classic()
    ggsave(g, filename = paste(path_output, "Histogram_number_of_gene_and_presence_in", group, "_data.png", sep = ""), height = 8, width = 8)
    
    #here we keep all gene present in the data
    gene_to_keep <- as.character(combined_gene_list$combined_gene_list)
    
    #construct the matrix patient x gene for mutations AND amp AND del
    patient_gene_mutation_matrix <- matrix(0, nrow = length(gene_to_keep), ncol = nbr_patient)
    colnames(patient_gene_mutation_matrix) <- patient_list
    rownames(patient_gene_mutation_matrix) <- gene_to_keep
    patient_gene_amp_matrix <- patient_gene_mutation_matrix
    patient_gene_del_matrix <- patient_gene_mutation_matrix
    total_mutation_per_gene_patient <- patient_gene_mutation_matrix
    total_amp_per_gene_patient <- patient_gene_mutation_matrix
    total_del_per_gene_patient <- patient_gene_mutation_matrix
    mutation_group_gene_to_keep <- mutation_group[which(mutation_group$gene_symbol %in% gene_to_keep),]
    amp_cnv_group_gene_to_keep <- amp_cnv_group[which(amp_cnv_group$genes_of_interest %in% gene_to_keep),]
    del_cnv_group_gene_to_keep <- del_cnv_group[which(del_cnv_group$genes_of_interest %in% gene_to_keep),]
    for (i in 1:dim(patient_gene_mutation_matrix)[2]) {
      tmp_mut <- mutation_group_gene_to_keep[which(mutation_group_gene_to_keep$Patient_name == patient_list[i]),]
      tmp_amp <- amp_cnv_group_gene_to_keep[which(amp_cnv_group_gene_to_keep$Patient_name == patient_list[i]),]
      tmp_del <- del_cnv_group_gene_to_keep[which(del_cnv_group_gene_to_keep$Patient_name == patient_list[i]),]
      if(dim(tmp_mut)[1] > 0){
        patient_gene_mutation_matrix[which(gene_to_keep %in% tmp_mut$gene_symbol),i] <- 1
      }
      if(dim(tmp_amp)[1] > 0){
        patient_gene_amp_matrix[which(gene_to_keep %in% tmp_amp$genes_of_interest),i] <- 1
      }
      if(dim(tmp_del)[1] > 0){
        patient_gene_del_matrix[which(gene_to_keep %in% tmp_del$genes_of_interest),i] <- 1
      }
      
      #might be usefull for late : matrices of patient X Gene with number of mutation/amp/del for each
      if(dim(tmp_mut)[1] > 0){
        tmp_gene_list <- unique(tmp_mut$gene_symbol)
        for (j in 1:length(tmp_gene_list)) {
          total_mutation_per_gene_patient[which(gene_to_keep == tmp_gene_list[j]),i] <- length(which(tmp_mut$gene_symbol == tmp_gene_list[j]))
        }
      }
      if(dim(tmp_amp)[1] > 0){
        tmp_gene_list <- unique(tmp_amp$genes_of_interest)
        for (j in 1:length(tmp_gene_list)) {
          total_amp_per_gene_patient[which(gene_to_keep == tmp_gene_list[j]),i] <- length(which(tmp_amp$genes_of_interest == tmp_gene_list[j]))
        }
      }
      if(dim(tmp_del)[1] > 0){
        tmp_gene_list <- unique(tmp_del$genes_of_interest)
        for (j in 1:length(tmp_gene_list)) {
          total_del_per_gene_patient[which(gene_to_keep == tmp_gene_list[j]),i] <- length(which(tmp_del$genes_of_interest == tmp_gene_list[j]))
        }
      }
      
    }#end for loop for each patient in matrix patient x gene for mutations
    
    #keep results with 1/0 in matrices for plots
    list_data[[count]] <- list(patient_gene_mutation_matrix,
                               patient_gene_amp_matrix,
                               patient_gene_del_matrix)
    names(list_data)[[count]] <- group
    
    count <- count + 1
    
    #save results matrices of patient X Gene with number of mutation/amp/del for each
    total_mutation_per_gene_patient <- cbind(data.frame(Gene = rownames(total_mutation_per_gene_patient)), as.data.frame(total_mutation_per_gene_patient))
    write_tsv(total_mutation_per_gene_patient, paste(path_output, group, "_total_mutation_per_gene_patient.tsv", sep = ""))
    total_amp_per_gene_patient <- cbind(data.frame(Gene = rownames(total_amp_per_gene_patient)), as.data.frame(total_amp_per_gene_patient))
    write_tsv(total_amp_per_gene_patient, paste(path_output, group, "_total_amp_per_gene_patient.tsv", sep = ""))
    total_del_per_gene_patient <- cbind(data.frame(Gene = rownames(total_del_per_gene_patient)), as.data.frame(total_del_per_gene_patient))
    write_tsv(total_del_per_gene_patient, paste(path_output, group, "_total_del_per_gene_patient.tsv", sep = ""))
  }
  
  
  clinical_data$New_DFS <- clinical_data$DFS
  clinical_data$New_DFS[which(clinical_data$New_DFS < 13)] <- "=<12"
  clinical_data$New_DFS[which(clinical_data$New_DFS > 12)] <- ">12"
  
  ##Ploting analysis
  global_summary <- data.frame(Group = group_to_plot, 
                               SNV = rep(0, length(group_to_plot)), 
                               CNV = rep(0, length(group_to_plot)), 
                               Combined = rep(0, length(group_to_plot)),
                               SNV_pathway = rep(0, length(group_to_plot)),
                               CNV_pathway = rep(0, length(group_to_plot)),
                               Combined_pathway = rep(0, length(group_to_plot)),
                               SNV_GO = rep(0, length(group_to_plot)),
                               CNV_GO = rep(0, length(group_to_plot)),
                               Combined_GO = rep(0, length(group_to_plot)))
  list_gene_set_result <- vector(mode = "list", length = length(group_to_plot))
  count <- 1
  for (analysis in analysis_to_do) {
    #for loop for each group to oncoprint (ASC, TuPr, TuPo)
    for (group in group_to_plot) {
      #load right data
      tmp_data <- list_data[[which(names(list_data) == group)]]
      tmp_snv = tmp_data[[1]]
      tmp_amp = tmp_data[[2]]
      tmp_del = tmp_data[[3]]
      
      patient_list <- colnames(tmp_snv)
      
      
      #TODO which geen to keep in oncoprint
      grid1_snv <- tmp_snv[which(rownames(tmp_snv) %in% c("BRCA1", "BRCA2", "GRID1")),]
      grid1_amp <- tmp_amp[which(rownames(tmp_amp) %in% c("BRCA1", "BRCA2", "GRID1")),]
      grid1_del <- tmp_del[which(rownames(tmp_del) %in% c("BRCA1", "BRCA2", "GRID1")),]
      
      
      #Filter gene list to keep gene present in cancer list AND at least present >= min_occurence_gene
      tmp_gene_list <- list_combined_gene[[which(names(list_combined_gene) == group)]]
      #TODO Change by group
      gene_to_keep <- as.character(tmp_gene_list$combined_gene_list[which(tmp_gene_list$Freq >= 2)])
      #gene_to_keep <- as.character(tmp_gene_list$combined_gene_list[which(tmp_gene_list$Freq >= min_occurence_gene)])
      gene_to_keep <- gene_to_keep[which(gene_to_keep %in% cancer_gene_list$Hugo_Symbol)]
      
      tmp_snv <- tmp_snv[which(rownames(tmp_snv) %in% gene_to_keep),]
      tmp_amp <- tmp_amp[which(rownames(tmp_amp) %in% gene_to_keep),]
      tmp_del <- tmp_del[which(rownames(tmp_del) %in% gene_to_keep),]
      #for latter to make summary of analysis like slide 57 from 10_02_23
      #dim(tmp_snv)
      #length(which(rowSums(tmp_snv) > 0))
      #length(which(rowSums(tmp_amp) > 0))
      #length(which(rowSums(tmp_del) > 0))
      
      #print(rowSums(tmp_snv) + rowSums(tmp_amp) + rowSums(tmp_del))
      if(analysis == "Default"){
        nbr_time_in_plot <- rowSums(tmp_snv) + rowSums(tmp_amp) + rowSums(tmp_del)
        
        id_amp <- which(rownames(tmp_amp) %in% cancer_gene_list$Hugo_Symbol[which(cancer_gene_list$Is_Oncogene == "No")])
        tmp_amp[id_amp,] <- 0
        
        id_del <- which(rownames(tmp_del) %in% cancer_gene_list$Hugo_Symbol[which(cancer_gene_list$Is_Tumor_Suppressor_Gene == "No")])
        tmp_del[id_del,] <- 0
        
        current_nbr_time_in_plot <- rowSums(tmp_snv) + rowSums(tmp_amp) + rowSums(tmp_del)
        #TODO change here to restrict oncoprint before it was == 0 for ASC, < 5 for TuPr and TuPo
        if(group == "ASC"){
          to_rm <- names(current_nbr_time_in_plot[which(current_nbr_time_in_plot == 0)])
        }else{
          to_rm <- names(current_nbr_time_in_plot[which(current_nbr_time_in_plot < 5)])
        }
        
        tmp_snv <- tmp_snv[-which(rownames(tmp_snv) %in% to_rm),]
        tmp_amp <- tmp_amp[-which(rownames(tmp_amp) %in% to_rm),]
        tmp_del <- tmp_del[-which(rownames(tmp_del) %in% to_rm),]
        
        ###TODO add the gene to the oncorpint
        tmp_snv <- rbind(tmp_snv, grid1_snv)
        rownames(tmp_snv)[length(rownames(tmp_snv))] <- "GRID1"
        tmp_amp <- rbind(tmp_amp, grid1_amp)
        rownames(tmp_amp)[length(rownames(tmp_amp))] <- "GRID1"
        tmp_del <- rbind(tmp_del, grid1_del)
        rownames(tmp_del)[length(rownames(tmp_del))] <- "GRID1"
        tmp_snv_new <- tmp_snv
        tmp_amp_new <- tmp_amp
        tmp_del_new <- tmp_del
        
        #for latter to make summary of analysis like slide 57 from 10_02_23
        #dim(tmp_snv)
        #length(which(rowSums(tmp_snv) > 0))
        #length(which(rowSums(tmp_amp) > 0))
        #length(which(rowSums(tmp_del) > 0))
      }
      
      
      ###Remove patient with no data 
      #TODO check if it true still
      to_rm_patient <- c()
      if(group == "ASC"){
        to_rm_patient <- c("CIND", "COVI", "CURS", "DIDA", "GNOL", "HIRO", "LUON", "PACK", "POWR", "REDI", "RENT", "SELO", "TYCO", "WILE", "XARA", "ZONA", "ZORO", "ZWAR")
      }else if(group == "TuPr"){
        #to_rm_patient <- c("NACH", "KDAU")
      }else if(group == "TuPo"){
        to_rm_patient <- c("DIDA", "LUON", "POWR", "WILE", "ZONA")
      }
      if(length(to_rm_patient) > 0){
        patient_list <- patient_list[-which(patient_list %in% to_rm_patient)]
        print(patient_list)
        tmp_snv <- tmp_snv[,-which(colnames(tmp_snv) %in% to_rm_patient)]
        tmp_amp <- tmp_amp[,-which(colnames(tmp_amp) %in% to_rm_patient)]
        tmp_del <- tmp_del[,-which(colnames(tmp_del) %in% to_rm_patient)]
        print(length(patient_list) - dim(tmp_snv)[2])  
      }
      
      
      #clinical data for plot
      clinical_data <- read_xlsx(clinical_data_path)
      #TODO as argument of the function : patient_to_rm, for the moment only remove the patient from the clinical data (carefull with facets/mutation)
      #patient_to_rm <- c("KDAU")
      
      clinical_data <- clinical_data[which(!is.na(clinical_data$Anapath_response)),]
      # clinical_data <- clinical_data[-which(clinical_data$Patient == patient_to_rm),]
      clinical_data$Anapath_response <- factor(clinical_data$Anapath_response,
                                               levels = c("Good", "Intermediate", "Bad"))
      clinical_data <- clinical_data %>%
        arrange(desc(DFS), Anapath_response)
      clinical_data <- clinical_data[which(clinical_data$Patient %in% patient_list),]
      clinical_data$New_DFS <- clinical_data$DFS
      clinical_data$New_DFS[which(clinical_data$New_DFS < 13)] <- "=<12"
      clinical_data$New_DFS[which(clinical_data$New_DFS > 12)] <- ">12"
      
      if(group == "TuPr"){
        ###Survival analysis based on https://doi.org/10.1016/j.ccell.2018.11.006
        ##SNV
        #Gene need to be mutated at least in 3 patient 
        #TODO change the parameter >= 5 as before see up 
        new_snv <- tmp_snv[which(rowSums(tmp_snv) >= 5),]
        result_cox_gene <- data.frame(Gene = rownames(new_snv), pvalue = NA, qvalue = NA, log_qvalue = NA, Frequency = NA, Hazard_ratio = NA)
        
        
        for (i in 1:dim(new_snv)[1]) {
          table_surv <- cbind(clinical_data[,which(colnames(clinical_data) %in% c("censored_DFS", "DFS"))], as.data.frame(t(new_snv))[,i])
          colnames(table_surv)[3] <- "gene"
          
          #Change DFS because package surminor use the opposit 
          new_DFS <- table_surv$censored_DFS
          table_surv$censored_DFS[which(new_DFS == 1)] <- 0
          table_surv$censored_DFS[which(new_DFS == 0)] <- 1
          #Proportional Hazards Regression Model
          fit <- coxph(Surv(DFS, censored_DFS) ~ gene,
                       data = table_surv)
          result_cox_gene$pvalue[i] <- summary(fit)$coefficients[5]
          
          HR <- cox.zph(fit, global = FALSE)
          result_cox_gene$pvalue[i] <- HR$table[3]
          result_cox_gene$Frequency[i] <- sum(table_surv$gene) / dim(table_surv)[1]
          result_cox_gene$Hazard_ratio[i] <- summary(fit)$coefficients[2]
        }
        #Mulitple correction
        result_cox_gene$qvalue <- p.adjust(result_cox_gene$pvalue, method = "BH")
        result_cox_gene$log_qvalue <- -log10(result_cox_gene$qvalue)
        result_cox_gene$sig <- "No"
        result_cox_gene$sig[which(result_cox_gene$qvalue < 0.05)] <- "Yes"
        
        #Plot
        #TODO try to change scale y 0-2, x center in 1
        gg <- ggplot(result_cox_gene, aes(x = Hazard_ratio, y = log_qvalue)) + 
          geom_point(aes(col=sig, size=Frequency)) + 
          geom_text_repel(aes(x = Hazard_ratio, y = log_qvalue, label = Gene)) +
          ylim(0, 2) +
          geom_hline(yintercept = 1.30103, linetype = "dashed", color = "red") +
          ylab("-log qvalue") +
          coord_cartesian(xlim=c(0.5, 1.5)) +
          theme_classic() 
        
        #save results
        write_xlsx(result_cox_gene, paste(path_output, "Summary_data_SNV_", group, ".xlsx", sep = ""))
        ggsave(gg, filename = paste(path_output, "Summary_plot_SNV_", group, ".png", sep = ""), height = 8, width = 8)
        
        ##CNV
        #combine AMP and Del into one dataframe
        tmp_cnv <- tmp_amp + tmp_del
        tmp_to_change <- which(tmp_cnv > 1)
        if(length(tmp_to_change) > 0){
          tmp_cnv[tmp_to_change] <- 1
        }
        #Gene need to have at least one AMP or DEL in at least in 1 patient 
        new_cnv <- tmp_cnv[which(rowSums(tmp_cnv) >= 5),]
        result_cox_gene <- data.frame(Gene = rownames(new_cnv), pvalue = NA, qvalue = NA, log_qvalue = NA, Frequency = NA, Hazard_ratio = NA)
        for (i in 1:dim(new_cnv)[1]) {
          table_surv <- cbind(clinical_data[,which(colnames(clinical_data) %in% c("censored_DFS", "DFS"))], as.data.frame(t(new_cnv))[,i])
          colnames(table_surv)[3] <- "gene"
          
          #Change DFS because package surminor use the opposit 
          new_DFS <- table_surv$censored_DFS
          table_surv$censored_DFS[which(new_DFS == 1)] <- 0
          table_surv$censored_DFS[which(new_DFS == 0)] <- 1
          #Proportional Hazards Regression Model
          fit <- coxph(Surv(DFS, censored_DFS) ~ gene,
                       data = table_surv)
          #result_cox_gene$pvalue[i] <- summary(fit)$coefficients[5]
          
          HR <- cox.zph(fit, global = FALSE)
          result_cox_gene$pvalue[i] <- HR$table[3]
          result_cox_gene$Frequency[i] <- sum(table_surv$gene) / dim(table_surv)[1]
          result_cox_gene$Hazard_ratio[i] <- summary(fit)$coefficients[2]
        }
        #Mulitple correction of -log10 pvalue
        result_cox_gene$qvalue <- p.adjust(result_cox_gene$pvalue, method = "BH")
        result_cox_gene$log_qvalue <- -log10(result_cox_gene$qvalue)
        result_cox_gene$sig <- "No"
        result_cox_gene$sig[which(result_cox_gene$qvalue < 0.05)] <- "Yes"
        
        #Plot
        gg <- ggplot(result_cox_gene, aes(x = Hazard_ratio, y = log_qvalue)) + 
          geom_point(aes(col=sig, size=Frequency)) + 
          geom_text_repel(aes(x = Hazard_ratio, y = log_qvalue, label = Gene), max.overlaps = 20) +
          ylim(0, 2) +
          geom_hline(yintercept = 1.30103, linetype = "dashed", color = "red") +
          ylab("-log qvalue") +
          coord_cartesian(xlim=c(0.5, 1.5)) +
          theme_classic()
        
        #save results
        write_xlsx(result_cox_gene, paste(path_output, "Summary_data_CNV_", group, ".xlsx", sep = ""))
        ggsave(gg, filename = paste(path_output, "Summary_plot_CNV_", group, ".png", sep = ""), height = 8, width = 8)
        
        ##Combined SNV + CNV
        tmp_combined <- tmp_snv + tmp_cnv
        tmp_to_change <- which(tmp_combined > 1)
        if(length(tmp_to_change) > 0){
          tmp_combined[tmp_to_change] <- 1
        }
        #Gene need to have at least one SNV or AMP or DEL in at least in 1 patient 
        new_combined <- tmp_combined[which(rowSums(tmp_combined) >= 5),]
        result_cox_gene <- data.frame(Gene = rownames(new_combined), pvalue = NA, qvalue = NA, log_qvalue = NA, Frequency = NA, Hazard_ratio = NA)
        for (i in 1:dim(new_combined)[1]) {
          table_surv <- cbind(clinical_data[,which(colnames(clinical_data) %in% c("censored_DFS", "DFS"))], as.data.frame(t(new_combined))[,i])
          colnames(table_surv)[3] <- "gene"
          
          #Change DFS because package surminor use the opposit 
          new_DFS <- table_surv$censored_DFS
          table_surv$censored_DFS[which(new_DFS == 1)] <- 0
          table_surv$censored_DFS[which(new_DFS == 0)] <- 1
          #Proportional Hazards Regression Model
          fit <- coxph(Surv(DFS, censored_DFS) ~ gene,
                       data = table_surv)
          #result_cox_gene$pvalue[i] <- summary(fit)$coefficients[5]
          
          HR <- cox.zph(fit, global = FALSE)
          result_cox_gene$pvalue[i] <- HR$table[3]
          result_cox_gene$Frequency[i] <- sum(table_surv$gene) / dim(table_surv)[1]
          result_cox_gene$Hazard_ratio[i] <- summary(fit)$coefficients[2]
        }
        #Mulitple correction of -log10 pvalue
        result_cox_gene$qvalue <- p.adjust(result_cox_gene$pvalue, method = "BH")
        result_cox_gene$log_qvalue <- -log10(result_cox_gene$qvalue)
        result_cox_gene$sig <- "No"
        result_cox_gene$sig[which(result_cox_gene$qvalue < 0.05)] <- "Yes"
        
        #Plot
        gg <- ggplot(result_cox_gene, aes(x = Hazard_ratio, y = log_qvalue)) + 
          geom_point(aes(col=sig, size=Frequency)) + 
          geom_text_repel(aes(x = Hazard_ratio, y = log_qvalue, label = Gene), max.overlaps = 15) +
          ylim(0, 2) +
          geom_hline(yintercept = 1.30103, linetype = "dashed", color = "red") +
          ylab("-log qvalue") +
          coord_cartesian(xlim=c(0.5, 1.5)) +
          theme_classic()
        
        #save results
        write_xlsx(result_cox_gene, paste(path_output, "Summary_data_Combined_SNV_CNV_", group, ".xlsx", sep = ""))
        ggsave(gg, filename = paste(path_output, "Summary_plot_Combined_SNV_CNV_", group, ".png", sep = ""), height = 8, width = 8)
        
        
        ###Gene set analysis for DFS > 12 et DFS < 12
        #Gene set for SNV for patient with DFS less than a year 
        DFS_less_snv <- tmp_snv[, which(colnames(tmp_snv) %in% clinical_data$Patient[which(clinical_data$DFS <= 12)])]
        gene_snv <- rownames(DFS_less_snv)[which(rowSums(DFS_less_snv) > 0)]
        data_gene_snv <- mutation_data[1:length(gene_snv),]
        data_gene_snv$gene_symbol <- gene_snv
        res_snv_DFS_small <- over_representation_analysis(geneList = unique(data_gene_snv$gene_symbol),
                                                          go_of_interest = c("BP", "MF", "CC"),
                                                          max_GO_similarity_accepted = 0.5,
                                                          cutoff = 0.05,
                                                          max_gene_per_item = 20,
                                                          max_item_plot = 20,
                                                          coocurrence = TRUE,
                                                          max_coocurrence = 100,
                                                          path_to_store_results = paste(path_output, paste(group, "SNV_DFSSmall_gene_set_analysis", sep = "_"), sep = "/"))
        
        #Gene set for SNV for patient with DFS more than a year 
        DFS_more_snv <- tmp_snv[, which(colnames(tmp_snv) %in% clinical_data$Patient[which(clinical_data$DFS > 12)])]
        gene_snv <- rownames(DFS_more_snv)[which(rowSums(DFS_more_snv) > 0)]
        data_gene_snv <- mutation_data[1:length(gene_snv),]
        data_gene_snv$gene_symbol <- gene_snv
        res_snv_DFS_big <- over_representation_analysis(geneList = unique(data_gene_snv$gene_symbol),
                                                        go_of_interest = c("BP", "MF", "CC"),
                                                        max_GO_similarity_accepted = 0.5,
                                                        cutoff = 0.05,
                                                        max_gene_per_item = 20,
                                                        max_item_plot = 20,
                                                        coocurrence = TRUE,
                                                        max_coocurrence = 100,
                                                        path_to_store_results = paste(path_output, paste(group, "SNV_DFSBig_gene_set_analysis", sep = "_"), sep = "/"))
        
        #Gene set for CNV (AMP + DEL)
        tmp_cnv <- tmp_amp + tmp_del
        tmp_to_change <- which(tmp_cnv > 1)
        if(length(tmp_to_change) > 0){
          tmp_cnv[tmp_to_change] <- 1
        }
        gene_cnv <- rownames(tmp_cnv)[which(rowSums(tmp_cnv) > 0)]
        data_gene_cnv <- mutation_data[1:length(gene_cnv),]
        data_gene_cnv$gene_symbol <- gene_cnv
        res_cnv <- over_representation_analysis(geneList = unique(data_gene_cnv$gene_symbol),
                                                go_of_interest = c("BP", "MF", "CC"),
                                                max_GO_similarity_accepted = 0.5,
                                                cutoff = 0.05,
                                                max_gene_per_item = 20,
                                                max_item_plot = 20,
                                                coocurrence = TRUE,
                                                max_coocurrence = 100,
                                                path_to_store_results = paste(path_output, paste(group, "CNV_gene_set_analysis", sep = "_"), sep = "/"))
        
        #Gene set for Combined SNV + CNV (AMP + DEL)
        tmp_combined <- tmp_snv + tmp_cnv
        tmp_to_change <- which(tmp_combined > 1)
        if(length(tmp_to_change) > 0){
          tmp_combined[tmp_to_change] <- 1
        }
        gene_combined <- rownames(tmp_combined)[which(rowSums(tmp_combined) > 0)]
        data_gene_combined <- mutation_data[1:length(gene_combined),]
        data_gene_combined$gene_symbol <- gene_combined
        res_combined <- over_representation_analysis(geneList = unique(data_gene_combined$gene_symbol),
                                                     go_of_interest = c("BP", "MF", "CC"),
                                                     max_GO_similarity_accepted = 0.5,
                                                     cutoff = 0.05,
                                                     max_gene_per_item = 20,
                                                     max_item_plot = 20,
                                                     coocurrence = TRUE,
                                                     max_coocurrence = 100,
                                                     path_to_store_results = paste(path_output, paste(group, "SNVandCNV_gene_set_analysis", sep = "_"), sep = "/"))
        
      }#end of if TuPr perform survival analysis
      
      
      ###New plots 
      tmp_cnv <- tmp_amp_new  + tmp_del_new
      tmp_to_change <- which(tmp_cnv > 1)
      if(length(tmp_to_change) > 0){
        tmp_cnv[tmp_to_change] <- 1
      }
      tmp_combined <- tmp_snv_new + tmp_cnv
      tmp_to_change <- which(tmp_combined > 1)
      if(length(tmp_to_change) > 0){
        tmp_combined[tmp_to_change] <- 1
      }
      tot <- dim(tmp_combined)[1] * length(unique(clinical_data$New_DFS))
      new_plot <- data.frame(matrix(NA, ncol = 3, nrow = tot)) 
      colnames(new_plot) <- c("Nbr_mutated", "Gene", "DFS")
      new_plot$Gene <- rep(rownames(tmp_combined), length(unique(clinical_data$New_DFS)))
      new_plot <- new_plot[order(new_plot$Gene),]
      new_plot$DFS <- rep(unique(clinical_data$New_DFS), dim(tmp_combined)[1])
      for(w in 1:dim(new_plot)[1]){
        tmp <- tmp_combined[which(rownames(tmp_combined) == new_plot$Gene[w]), clinical_data$Patient[which(clinical_data$New_DFS == new_plot$DFS[w])]]
        if(length(tmp) > 0){
          new_plot$Nbr_mutated[w] <- sum(tmp)
        }else{
          new_plot$Nbr_mutated[w] <- 0
        }
      }
      
      
      #Plot mutation per gene
      p1 <- ggplot(new_plot[new_plot$DFS == "=<12", ], aes(x = Nbr_mutated, y = Gene)) +
        geom_col(fill = "steelblue") +
        scale_x_reverse() +
        labs(x = "",y="") +
        theme_classic() +
        theme(axis.title.y=element_blank(),
              axis.ticks.y= element_blank(),
              axis.text.y = element_blank(),
              axis.line = element_blank())
      
      p2 <- ggplot(new_plot[new_plot$DFS == ">12", ], aes(x = Nbr_mutated, y = Gene)) +
        geom_col(fill = "darkorange") +
        labs(x = "",y="") +
        theme_classic() +
        theme(axis.title.y =element_blank(),
              axis.ticks.y= element_blank(),
              axis.text.y = element_blank(),
              axis.line = element_blank())
      
      pmid <- ggplot(new_plot,aes(x=1,y=Gene))+
        geom_text(aes(label=Gene))+
        ylab(NULL)+
        xlab("")+
        theme_classic() +
        theme(axis.title.y=element_blank(),
              axis.ticks.x= element_blank(),
              axis.title.x = element_text(face = "bold",hjust  =1),
              axis.ticks.y= element_blank(),
              axis.text.x = element_blank(),
              axis.text.y = element_blank(),
              axis.line = element_blank())
      
      #Plot assembly
      col1 = plot_grid(p1, ncol = 1,
                       align = "v")
      #TODO change 0.02 to make sure gene name are on the same level has bar plot 
      col_mid = plot_grid(pmid, NULL, ncol = 1,
                          rel_heights = c(1,0.02), align = "v")
      col2 = plot_grid(p2, ncol = 1,
                       align = "v")
      plot_total = plot_grid(col1,col_mid, col2, nrow = 1, rel_widths = c(1,0.25,1), align = "v")
      
      #Plot save
      size_pdf <- c(1.2*8, 1.2*5)
      pdf(paste(path_output, "Nbr_mut_by_gene_DFS_", group, ".pdf", sep = ""),
          width = unit(size_pdf[1],"cm"),
          height = unit(size_pdf[2],"cm"))
      print(plot_total)
      dev.off()
      
      
      
      #save results
      if(group == "TuPr"){
        write_xlsx(result_cox_gene, paste(path_output, "Summary_data_Combined_SNV_CNV_", group, ".xlsx", sep = ""))
        ggsave(gg, filename = paste(path_output, "Summary_plot_Combined_SNV_CNV_", group, ".png", sep = ""), height = 8, width = 8)
      }
      
      
      ############# Oncoprint
      #create a list of the NGS data matrices
      patient_order <- clinical_data$Patient
      
      # Check if all the columns in patient_order exist in tmp_snv
      missing_columns <- setdiff(patient_order, colnames(tmp_snv))
      if (length(missing_columns) > 0) {
        patient_order <- patient_order[-which(patient_order %in% missing_columns)]
      }
      
      # Reorder the columns of tmp_snv according to patient_order
      tmp_snv <- tmp_snv[, patient_order]
      tmp_amp <- tmp_amp[, patient_order]
      tmp_del <- tmp_del[, patient_order]
      if(group == "ASC"){
        new_rows <- matrix(0, nrow = 2, ncol = ncol(tmp_snv))
        rownames(new_rows) <- c("BRCA1", "BRCA2")
        tmp_snv <- rbind(tmp_snv, new_rows)
        tmp_amp <- rbind(tmp_amp, new_rows)
        tmp_del <- rbind(tmp_del, new_rows)
        
        tmp_germline <- tmp_snv
        tmp_germline[which(tmp_germline == 1)] <- 0
        tmp_germline[which(rownames(tmp_germline) == "BRCA1"),which(colnames(tmp_germline) %in% c("CYLO", "VOBE", "CANE", "DADA", "XARA", "ZORO"))] <- 1
        tmp_germline[which(rownames(tmp_germline) == "BRCA2"),which(colnames(tmp_germline) %in% c("FETT"))] <- 1
      }
      if(group == "TuPr"){
        tmp_germline <- tmp_snv
        tmp_germline[which(tmp_germline == 1)] <- 0
        tmp_germline[which(rownames(tmp_germline) == "BRCA1"),which(colnames(tmp_germline) %in% c("CYLO", "VOBE", "CANE", "DADA", "XARA", "ZORO"))] <- 1
        tmp_germline[which(rownames(tmp_germline) == "BRCA2"),which(colnames(tmp_germline) %in% c("FETT"))] <- 1
      }
      if(group == "TuPo"){
        tmp_snv <- tmp_snv[-42,]
        tmp_amp <- tmp_amp[-42,]
        tmp_del <- tmp_del[-42,]
        tmp_germline <- tmp_snv
        tmp_germline[which(tmp_germline == 1)] <- 0
        tmp_germline[which(rownames(tmp_germline) == "BRCA1"),which(colnames(tmp_germline) %in% c("CYLO", "VOBE", "CANE", "DADA", "XARA", "ZORO"))] <- 1
        tmp_germline[which(rownames(tmp_germline) == "BRCA2"),which(colnames(tmp_germline) %in% c("FETT"))] <- 1
      }
      
      
      mat_list <- list(somatic = tmp_snv, 
                       amp = tmp_amp,
                       del = tmp_del,
                       germline = tmp_germline)
      
      #Apply the oncoprint function
      col = c("del" = "blue", "amp" = "red", "somatic" = "#008000", "germline" = "green")
      alter_fun = list(
        background = alter_graphic("rect", fill = "#CCCCCC"),   
        amp = alter_graphic("rect", fill = col["amp"]),
        del = alter_graphic("rect", fill = col["del"]),
        somatic = alter_graphic("rect", height = 0.33, fill = col["somatic"]),
        germline = alter_graphic("rect", height = 0.5, fill = col["germline"])
      )
      column_title = paste("OncoPrint for HGSOC -", group, "samples")
      heatmap_legend_param = list(title = "Alterations", at = c("amp", "del", "somatic", "germline"), 
                                  labels = c("amp", "del", "somatic", "germline"))
      
      x1_clinical <- as.character(clinical_data$Anapath_response)
      x2_clinical <- clinical_data$BRCA
      x3_clinical <- clinical_data$Nombre_de_cures_NACT
      x4_clinical <- clinical_data$CA125_post
      x5_clinical <- clinical_data$PFI
      y_clinical <- clinical_data$DFS
      
      #automaticaly adapt heigth of plot given number of gene to be displayed
      size_for_plot <- length(which(rowSums(tmp_snv) + rowSums(tmp_amp) + rowSums(tmp_del) > 0))
      val_height <- 25 * size_for_plot
      
      #change name of plot if other analysis
      #if(analysis == "oncoGene_and_tumorSupr"){
      #  name_of_plot <- paste(path_output, "oncoPrint_", analysis, "_", group, ".png", sep = "")
      #}else{
      #Default
      name_of_plot <- paste(path_output, "oncoPrint_", group, ".png", sep = "")
      #}
      
      png(name_of_plot,
          width = 880, height = val_height)
      p <- oncoPrint(mat_list,
                     alter_fun = alter_fun, 
                     col = col, 
                     column_order = patient_order,
                     top_annotation = HeatmapAnnotation(column_barplot = anno_oncoprint_barplot(show_fraction = F)),
                     bottom_annotation = HeatmapAnnotation('Disease-free survival' = anno_barplot(y_clinical, 
                                                                              gp = gpar(fill = ifelse(y_clinical > 12, "#67a9cf", "#ef8a62")), 
                                                                              height = unit(3, "cm"), 
                                                                              annotation_label = "Disease-free survival"),
                                                           'Pathological response' = x1_clinical, 
                                                           'Germline BRCA1/2 mut' = x2_clinical,
                                                           'Cycles neoadjuvant chemo' = x3_clinical,
                                                           CA125 = x4_clinical,
                                                           'Platinum-free interval' = x5_clinical,
                                                           name = c(anapath_response = 'Pathological response', BRCA_mut = 'Germline BRCA1/2 mut', Nbr_cure_Nact = 'Cycles neoadjuvant chemo', CA125 = "CA125", PFI = 'Platinum-free interval'),
                                                           col = list('Pathological response' = c("Good" = "green", "Intermediate"="orange", "Bad"="red"), 
                                                                      'Germline BRCA1/2 mut' = c("Yes" = "#31a354", "No"="#e5f5e0", "Unknown"="#FFFFFF"),
                                                                      'Cycles neoadjuvant chemo' = c("3" = "#FFFF00", "4"="#FFCC00", "6"="#FF6600"),
                                                                      CA125 = c("Good" = "#636363", "Intermediate"="#bdbdbd", "Bad"="#f0f0f0"),
                                                                      'Platinum-free interval' = c("platinum sensitive" = "#0033FF", "semi sensitive" = "#0099FF", "platinum resistant" = "#33CCFF"))),
                     right_annotation = rowAnnotation(row_barplot = anno_oncoprint_barplot(show_fraction = T)),
                     pct_side = "right", 
                     row_names_side = "left",
                     remove_empty_rows = T,
                     show_column_names = T,
                     column_title = column_title, 
                     heatmap_legend_param = heatmap_legend_param)
      draw(p)
      dev.off()
      
      
      
      #ONLY TuPr
      if(group == "TuPr"){
        tmp_TuPr <- enrich_mutation_data[grep(enrich_mutation_data$sample, pattern = group),]
        tmp_gene <- unique(tmp_TuPr$gene_symbol)
        tmp_enriched <- matrix(0, ncol = length(patient_list), nrow = length(tmp_gene)) 
        colnames(tmp_enriched) <- patient_list
        rownames(tmp_enriched) <- tmp_gene
        tmp_depleted <- tmp_enriched
        for (i in 1:dim(tmp_TuPr)[1]) {
          tmp_gene <- tmp_TuPr$gene_symbol[i]
          tmp_patient <- tmp_TuPr$Patient_name[i]
          tmp_statut <- tmp_TuPr$Statut[i]
          if(tmp_statut == "Enriched"){
            tmp_enriched[which(rownames(tmp_enriched) == tmp_gene), which(colnames(tmp_enriched) == tmp_patient)] <- 1 +
              tmp_enriched[which(rownames(tmp_enriched) == tmp_gene), which(colnames(tmp_enriched) == tmp_patient)]
          }else if(tmp_statut == "Depleted"){
            tmp_depleted[which(rownames(tmp_depleted) == tmp_gene), which(colnames(tmp_depleted) == tmp_patient)] <- 1 +
              tmp_depleted[which(rownames(tmp_depleted) == tmp_gene), which(colnames(tmp_depleted) == tmp_patient)]
          }
        }
        current_nbr_time_in_plot <- rowSums(tmp_enriched) + rowSums(tmp_depleted)
        #TODO change thresold nbr time must be present to limit oncoprint, here set to 2
        to_rm <- names(current_nbr_time_in_plot[which(current_nbr_time_in_plot < 3)])
        tmp_enriched <- tmp_enriched[-which(rownames(tmp_enriched) %in% to_rm),]
        tmp_depleted <- tmp_depleted[-which(rownames(tmp_depleted) %in% to_rm),]
        
        ############# Oncoprint
        #create a list of the NGS data matrices
        mat_list <- list(enrich = tmp_enriched,
                         depleted = tmp_depleted)
        
        size_for_plot <- length(which(rowSums(tmp_enriched) + rowSums(tmp_depleted) > 0))
        val_height <- 25 * size_for_plot
        #Apply the oncoprint function
        col = c("enrich" = "red", "depleted" = "blue")
        alter_fun = list(
          background = alter_graphic("rect", fill = "#CCCCCC"),   
          enrich = alter_graphic("rect", fill = col["enrich"]),
          depleted = alter_graphic("rect", fill = col["depleted"])
        )
        column_title = paste("OncoPrint for HGSOC -", group, "samples")
        heatmap_legend_param = list(title = "Alterations", at = c("enrich", "depleted"), 
                                    labels = c("enrich", "depleted"))
        
        clinical_data <- clinical_data %>%
          arrange(desc(DFS), Anapath_response)
        x1_clinical <- as.character(clinical_data$Anapath_response)
        x2_clinical <- clinical_data$BRCA
        x3_clinical <- clinical_data$Nombre_de_cures_NACT
        x4_clinical <- clinical_data$CA125_post
        x5_clinical <- clinical_data$PFI
        y_clinical <- clinical_data$DFS
        name_of_plot <- paste(path_output, "oncoPrint_DFS_only_depleted_", group, ".png", sep = "")
        png(name_of_plot,
            width = 880, height = 400)
        p <- oncoPrint(mat_list,
                       alter_fun = alter_fun, 
                       col = col, 
                       column_order = patient_list,
                       top_annotation = HeatmapAnnotation(column_barplot = anno_oncoprint_barplot(show_fraction = F)),
                       bottom_annotation = HeatmapAnnotation(DFS = anno_barplot(y_clinical, 
                                                                                gp = gpar(fill = ifelse(y_clinical > 12, "#67a9cf", "#ef8a62")), 
                                                                                height = unit(3, "cm"), 
                                                                                annotation_label = "DFS"),
                                                             anapath_response = x1_clinical, 
                                                             BRCA_mut = x2_clinical,
                                                             Nbr_cure_Nact = x3_clinical,
                                                             CA125 = x4_clinical,
                                                             PFI = x5_clinical,
                                                             name = c(anapath_response = "anapath_response", BRCA_mut = "BRCA_mut", Nbr_cure_Nact = "Nbr_cure_Nact", CA125 = "CA125", PFI = "PFI"),
                                                             col = list(anapath_response = c("Good" = "green", "Intermediate"="orange", "Bad"="red"), 
                                                                        BRCA_mut = c("Yes" = "#31a354", "No"="#e5f5e0", "Unknown"="#FFFFFF"),
                                                                        Nbr_cure_Nact = c("3" = "#FFFF00", "4"="#FFCC00", "6"="#FF6600"),
                                                                        CA125 = c("Good" = "#636363", "Intermediate"="#bdbdbd", "Bad"="#f0f0f0"),
                                                                        PFI = c("platinum sensitive" = "#0033FF", "semi sensitive" = "#0099FF", "platinum resistant" = "#33CCFF"))),
                       right_annotation = rowAnnotation(row_barplot = anno_oncoprint_barplot(show_fraction = T)),
                       pct_side = "right", 
                       row_names_side = "left",
                       remove_empty_rows = T,
                       show_column_names = T,
                       column_title = column_title, 
                       heatmap_legend_param = heatmap_legend_param)
        draw(p)
        dev.off()
      }
      
      
      
      if(group == "TuPo"){
        tmp_TuPo <- enrich_mutation_data[grep(enrich_mutation_data$sample, pattern = group),]
        tmp_gene <- unique(tmp_TuPo$gene_symbol)
        tmp_enriched <- matrix(0, ncol = length(patient_list), nrow = length(tmp_gene)) 
        colnames(tmp_enriched) <- patient_list
        rownames(tmp_enriched) <- tmp_gene
        tmp_depleted <- tmp_enriched
        for (i in 1:dim(tmp_TuPo)[1]) {
          tmp_gene <- tmp_TuPo$gene_symbol[i]
          tmp_patient <- tmp_TuPo$Patient_name[i]
          tmp_statut <- tmp_TuPo$Statut[i]
          if(tmp_statut == "Enriched"){
            tmp_enriched[which(rownames(tmp_enriched) == tmp_gene), which(colnames(tmp_enriched) == tmp_patient)] <- 1 +
              tmp_enriched[which(rownames(tmp_enriched) == tmp_gene), which(colnames(tmp_enriched) == tmp_patient)]
          }else if(tmp_statut == "Depleted"){
            tmp_depleted[which(rownames(tmp_depleted) == tmp_gene), which(colnames(tmp_depleted) == tmp_patient)] <- 1 +
              tmp_depleted[which(rownames(tmp_depleted) == tmp_gene), which(colnames(tmp_depleted) == tmp_patient)]
          }
        }
        current_nbr_time_in_plot <- rowSums(tmp_enriched) + rowSums(tmp_depleted)
        #TODO change thresold nbr time must be present to limit oncoprint, here set to 2
        to_rm <- names(current_nbr_time_in_plot[which(current_nbr_time_in_plot < 2)])
        tmp_enriched <- tmp_enriched[-which(rownames(tmp_enriched) %in% to_rm),]
        tmp_depleted <- tmp_depleted[-which(rownames(tmp_depleted) %in% to_rm),]
        
        ############# Oncoprint
        #create a list of the NGS data matrices
        mat_list <- list(enrich = tmp_enriched,
                         depleted = tmp_depleted)
        
        size_for_plot <- length(which(rowSums(tmp_enriched) + rowSums(tmp_depleted) > 0))
        val_height <- max(c(25 * size_for_plot, 500))
        #Apply the oncoprint function
        col = c("enrich" = "red", "depleted" = "blue")
        alter_fun = list(
          background = alter_graphic("rect", fill = "#CCCCCC"),   
          enrich = alter_graphic("rect", fill = col["enrich"]),
          depleted = alter_graphic("rect", fill = col["depleted"])
        )
        column_title = paste("OncoPrint for HGSOC -", group, "samples")
        heatmap_legend_param = list(title = "Alterations", at = c("enrich", "depleted"), 
                                    labels = c("enrich", "depleted"))
        
        clinical_data <- clinical_data %>%
          arrange(desc(DFS), Anapath_response)
        x1_clinical <- as.character(clinical_data$Anapath_response)
        x2_clinical <- clinical_data$BRCA
        x3_clinical <- clinical_data$Nombre_de_cures_NACT
        x4_clinical <- clinical_data$CA125_post
        x5_clinical <- clinical_data$PFI
        y_clinical <- clinical_data$DFS
        name_of_plot <- paste(path_output, "oncoPrint_DFS_only_depleted_", group, ".png", sep = "")
        png(name_of_plot,
            width = 880, height = val_height)
        p <- oncoPrint(mat_list,
                       alter_fun = alter_fun, 
                       col = col, 
                       column_order = patient_list,
                       top_annotation = HeatmapAnnotation(column_barplot = anno_oncoprint_barplot(show_fraction = F)),
                       bottom_annotation = HeatmapAnnotation(DFS = anno_barplot(y_clinical, 
                                                                                gp = gpar(fill = ifelse(y_clinical > 12, "#67a9cf", "#ef8a62")), 
                                                                                height = unit(3, "cm"), 
                                                                                annotation_label = "DFS"),
                                                             anapath_response = x1_clinical, 
                                                             BRCA_mut = x2_clinical,
                                                             Nbr_cure_Nact = x3_clinical,
                                                             CA125 = x4_clinical,
                                                             PFI = x5_clinical,
                                                             name = c(anapath_response = "anapath_response", BRCA_mut = "BRCA_mut", Nbr_cure_Nact = "Nbr_cure_Nact", CA125 = "CA125", PFI = "PFI"),
                                                             col = list(anapath_response = c("Good" = "green", "Intermediate"="orange", "Bad"="red"), 
                                                                        BRCA_mut = c("Yes" = "#31a354", "No"="#e5f5e0", "Unknown"="#FFFFFF"),
                                                                        Nbr_cure_Nact = c("3" = "#FFFF00", "4"="#FFCC00", "6"="#FF6600"),
                                                                        CA125 = c("Good" = "#636363", "Intermediate"="#bdbdbd", "Bad"="#f0f0f0"),
                                                                        PFI = c("platinum sensitive" = "#0033FF", "semi sensitive" = "#0099FF", "platinum resistant" = "#33CCFF"))),
                       right_annotation = rowAnnotation(row_barplot = anno_oncoprint_barplot(show_fraction = T)),
                       pct_side = "right", 
                       row_names_side = "left",
                       remove_empty_rows = T,
                       show_column_names = T,
                       column_title = column_title, 
                       heatmap_legend_param = heatmap_legend_param)
        draw(p)
        dev.off()
      }
      
      
      
      count <- count + 1
    }#end for loop for each group to oncoprint 
  }#end loop for each analysis
  #Save general info 
  write_xlsx(global_summary, paste(path_output, "Summary_Nbr_gene.xlsx", sep = ""))
  
  
}#end of function
